### ISSUE TITLE
[WIP] 社内サイネージのアイディア

### ISSUE THREAD

**Issue by kazup0n** [kazup0n/fboard#8]
### アイディア箇条書き
- slackから`@efbot speech ほげほげ` で :moyai: < ほげほげ としゃべる（音声がでる)
- スケジュールと内容を設定しておくと自動で音声通知する
  - スプレッドシートにテキストとスケジュールを入力する
- サイネージのようにスライドが表示される
  - 一定時間で切り替え
  - 内容はスプレッドシートに登録(１行１ページ)
  - 表示期間の設定可
### 実装メモ
- https://github.com/ncb000gt/node-cron
- https://www.npmjs.com/package/google-spreadsheet

**Comment by kazup0n** [comment]
- 追加する機能を`ScheduledSpeech` および`ScheduledSlides`と名付ける
- どちらもfirebase上のデータとクライアント側の実装で実現する
- ユーザーはスプレッドシートに入力して、`efbot`が定期的にシートをみて、firebase上のデータを更新する

### Scheduled Speech

speech オブジェクト

``` yaml
message: "this is scheduled message",
type: "cron"
schedule: { crontab: "<crontab notation>"}
```

### ScheduledSlides

slideオブジェクト

``` yaml
title: title of slide
body: "body can contain multiple lines.\n - one\n - two \n  -three",
issuedAt:  "YYYY-MM-DDThh:mm:ssTZD"
expiredAt: "YYYY-MM-DDThh:mm:ssTZD"
```
- `expiredAt` を過ぎたら削除される
- `issedAt` をすぎないと表示されない
